// ─────────────────────────────────────────────────────────────────────────────
// Schema-Risk — Markdown Formatter (CI/PR comments)
// ─────────────────────────────────────────────────────────────────────────────

import type { MigrationReport } from '../types.js';
import { RiskLevel, riskGte } from '../types.js';

function riskEmoji(level: RiskLevel): string {
  switch (level) {
    case RiskLevel.Low:
      return '🟢';
    case RiskLevel.Medium:
      return '🟡';
    case RiskLevel.High:
      return '🟠';
    case RiskLevel.Critical:
      return '🔴';
  }
}

export function renderMarkdown(reports: MigrationReport[]): string {
  const lines: string[] = [];

  const maxRisk = reports.reduce<RiskLevel>(
    (acc, r) => (riskGte(r.overallRisk, acc) ? r.overallRisk : acc),
    RiskLevel.Low,
  );

  lines.push(`## 🛡️ SchemaRisk — Migration Safety Report (PostgreSQL ${reports[0]?.pgVersion ?? 14})`);
  lines.push('');

  // Summary table
  lines.push('| File | Risk | Score | Lock Duration | Maintenance Window |');
  lines.push('|------|:----:|------:|--------------:|:------------------:|');

  for (const report of reports) {
    const lockStr = report.estimatedLockSeconds != null
      ? report.estimatedLockSeconds >= 60
        ? `~${Math.floor(report.estimatedLockSeconds / 60)}m`
        : `~${report.estimatedLockSeconds}s`
      : '—';
    const mw = report.requiresMaintenanceWindow ? '⚠️ YES' : '—';
    lines.push(
      `| \`${report.file}\` | ${riskEmoji(report.overallRisk)} **${report.overallRisk}** | ${report.score} | ${lockStr} | ${mw} |`,
    );
  }

  lines.push('');

  // Details per report
  for (const report of reports) {
    if (report.operations.length === 0) continue;

    lines.push(`### ${report.file}`);
    lines.push('');

    // Warnings
    if (report.warnings.length > 0) {
      lines.push('**Warnings:**');
      for (const w of report.warnings) {
        lines.push(`- ⚠️ ${w}`);
      }
      lines.push('');
    }

    // Recommendations
    if (report.recommendations.length > 0) {
      lines.push('**Safe Alternatives:**');
      for (const r of report.recommendations) {
        lines.push(`\`\`\`sql`);
        lines.push(r);
        lines.push('```');
      }
      lines.push('');
    }
  }

  // Footer
  if (riskGte(maxRisk, RiskLevel.High)) {
    lines.push('> ⛔ **This migration should NOT be deployed without review.**');
  } else if (riskGte(maxRisk, RiskLevel.Medium)) {
    lines.push('> ⚠️ **Review recommended before deploying.**');
  } else {
    lines.push('> ✅ **Migration looks safe.**');
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [SchemaRisk](https://github.com/Keystones-Lab/schema-risk-npm)*');
  lines.push('');

  return lines.join('\n');
}
