// ─────────────────────────────────────────────────────────────────────────────
// Schema-Risk — Configuration Loader
// ─────────────────────────────────────────────────────────────────────────────

import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { RiskLevel, parseRiskLevel } from '../types.js';
import type { SchemaRiskConfig } from '../types.js';

const CONFIG_FILENAMES = ['schema-risk.yml', 'schema-risk.yaml', '.schema-risk.yml'];

const DEFAULT_CONFIG: SchemaRiskConfig = {
  version: 2,
  thresholds: {
    failOn: RiskLevel.High,
    guardOn: RiskLevel.Medium,
  },
  rules: {
    disabled: [],
    tableOverrides: {},
  },
  scan: {
    rootDir: '.',
    extensions: ['rs', 'py', 'go', 'ts', 'js', 'rb', 'java', 'kt'],
    exclude: ['target/', 'node_modules/', 'vendor/', '.git/', 'dist/'],
  },
  output: {
    format: 'terminal',
    color: true,
    showRecommendations: true,
  },
};

export function loadConfig(configPath?: string): SchemaRiskConfig {
  if (configPath) {
    const abs = resolve(configPath);
    if (!existsSync(abs)) {
      throw new Error(`Config file not found: ${abs}`);
    }
    return mergeConfig(parseConfigFile(abs));
  }

  for (const name of CONFIG_FILENAMES) {
    const abs = resolve(process.cwd(), name);
    if (existsSync(abs)) {
      return mergeConfig(parseConfigFile(abs));
    }
  }

  return { ...DEFAULT_CONFIG };
}

export function getDefaultConfig(): SchemaRiskConfig {
  return { ...DEFAULT_CONFIG };
}

export function generateConfigFile(outputPath: string): void {
  const template = `# schema-risk.yml — per-project SchemaRisk configuration
# Generated by: schema-risk init
version: 2

thresholds:
  fail_on: high          # low | medium | high | critical
  guard_on: medium       # operations at this level or above trigger guard prompts

rules:
  disabled: []           # e.g. [R03, R07]
  table_overrides: {}

scan:
  root_dir: "."
  extensions: [rs, py, go, ts, js, rb, java, kt]
  exclude: [target/, node_modules/, vendor/, .git/]

output:
  format: terminal       # terminal | json | markdown | sarif
  color: true
  show_recommendations: true
`;
  writeFileSync(outputPath, template, 'utf-8');
}

// ─────────────────────────────────────────────────────────────────────────────
// Internal
// ─────────────────────────────────────────────────────────────────────────────

interface RawConfig {
  version?: number;
  thresholds?: { fail_on?: string; guard_on?: string };
  rules?: {
    disabled?: string[];
    table_overrides?: Record<string, { max_risk?: string; ignored?: boolean }>;
  };
  scan?: {
    root_dir?: string;
    extensions?: string[];
    exclude?: string[];
  };
  output?: {
    format?: string;
    color?: boolean;
    show_recommendations?: boolean;
  };
}

function parseConfigFile(filePath: string): Partial<SchemaRiskConfig> {
  const content = readFileSync(filePath, 'utf-8');
  const raw = parseYaml(content) as RawConfig | null;
  if (!raw || typeof raw !== 'object') return {};

  const result: Partial<SchemaRiskConfig> = {};

  if (raw.version != null) result.version = raw.version;

  if (raw.thresholds) {
    result.thresholds = {
      failOn: raw.thresholds.fail_on
        ? parseRiskLevel(raw.thresholds.fail_on)
        : DEFAULT_CONFIG.thresholds.failOn,
      guardOn: raw.thresholds.guard_on
        ? parseRiskLevel(raw.thresholds.guard_on)
        : DEFAULT_CONFIG.thresholds.guardOn,
    };
  }

  if (raw.rules) {
    const overrides: Record<string, { maxRisk?: RiskLevel; ignored?: boolean }> = {};
    if (raw.rules.table_overrides) {
      for (const [table, override] of Object.entries(raw.rules.table_overrides)) {
        overrides[table] = {
          maxRisk: override.max_risk ? parseRiskLevel(override.max_risk) : undefined,
          ignored: override.ignored ?? false,
        };
      }
    }
    result.rules = {
      disabled: raw.rules.disabled ?? [],
      tableOverrides: overrides,
    };
  }

  if (raw.scan) {
    result.scan = {
      rootDir: raw.scan.root_dir ?? DEFAULT_CONFIG.scan.rootDir,
      extensions: raw.scan.extensions ?? DEFAULT_CONFIG.scan.extensions,
      exclude: raw.scan.exclude ?? DEFAULT_CONFIG.scan.exclude,
    };
  }

  if (raw.output) {
    const format = raw.output.format ?? 'terminal';
    const validFormats = ['terminal', 'json', 'markdown', 'sarif'] as const;
    result.output = {
      format: (validFormats.includes(format as (typeof validFormats)[number])
        ? format
        : 'terminal') as SchemaRiskConfig['output']['format'],
      color: raw.output.color ?? true,
      showRecommendations: raw.output.show_recommendations ?? true,
    };
  }

  return result;
}

function mergeConfig(partial: Partial<SchemaRiskConfig>): SchemaRiskConfig {
  return {
    version: partial.version ?? DEFAULT_CONFIG.version,
    thresholds: { ...DEFAULT_CONFIG.thresholds, ...partial.thresholds },
    rules: {
      disabled: partial.rules?.disabled ?? DEFAULT_CONFIG.rules.disabled,
      tableOverrides: {
        ...DEFAULT_CONFIG.rules.tableOverrides,
        ...partial.rules?.tableOverrides,
      },
    },
    scan: { ...DEFAULT_CONFIG.scan, ...partial.scan },
    output: { ...DEFAULT_CONFIG.output, ...partial.output },
  };
}
